import Foundation
import SwiftData

/// SwiftData persistence record for a single chat message.
///
/// Mirrors the `messages` table in the Flutter app. Image attachments are
/// stored as opaque `Data` here; the binding to the file system is deferred
/// until Phase 6.
///
/// `role` is stored as a `String` (the raw value of `OllamaMessage.Role`)
/// rather than the enum directly because iOS 17/18 SwiftData crashes when
/// persisting raw-representable enums in `@Model`. The `role` computed
/// property hides that detail from callers.
@Model
final class MessageRecord {
    var id: UUID = UUID()
    var content: String = ""
    var model: String?
    var createdAt: Date = Date()
    var imagesData: Data?

    /// Raw value of `OllamaMessage.Role`. Use the `role` computed property.
    /// Not marked `private` because the @Model macro skips private stored
    /// properties, which silently breaks persistence.
    var roleRaw: String = "user"

    /// Tokens generated by the model.
    var evalCount: Int?
    /// Time spent generating, in nanoseconds.
    var evalDuration: Int?
    /// Wall-clock duration for the whole request, in nanoseconds.
    var totalDuration: Int?

    var chat: ChatRecord?

    init(
        id: UUID = UUID(),
        content: String,
        role: OllamaMessage.Role,
        model: String? = nil,
        createdAt: Date = Date(),
        imagesData: Data? = nil
    ) {
        self.id = id
        self.content = content
        self.model = model
        self.createdAt = createdAt
        self.imagesData = imagesData
        self.roleRaw = role.rawValue
    }
}

extension MessageRecord {
    var role: OllamaMessage.Role {
        get { OllamaMessage.Role(rawValue: roleRaw) ?? .user }
        set { roleRaw = newValue.rawValue }
    }

    /// Formatted generation stats, e.g. "gemma4:latest · 38 tok · 24.3 tok/s · 1.2s"
    var statsText: String? {
        guard let evalCount, evalCount > 0 else { return nil }
        var parts: [String] = []
        if let model, !model.isEmpty { parts.append(model) }
        parts.append("\(evalCount) tok")
        if let evalDuration, evalDuration > 0 {
            let tokPerSec = Double(evalCount) / (Double(evalDuration) / 1_000_000_000)
            parts.append(String(format: "%.1f tok/s", tokPerSec))
        }
        if let totalDuration, totalDuration > 0 {
            let seconds = Double(totalDuration) / 1_000_000_000
            parts.append(String(format: "%.1fs", seconds))
        }
        return parts.joined(separator: " · ")
    }

    static func make(from message: OllamaMessage) -> MessageRecord {
        MessageRecord(
            id: message.id,
            content: message.content,
            role: message.role,
            model: message.model,
            createdAt: message.createdAt,
            imagesData: message.images?.first
        )
    }

    /// Message content with Markdown syntax stripped to plain text.
    var plainContent: String {
        let options = AttributedString.MarkdownParsingOptions(
            interpretedSyntax: .inlineOnlyPreservingWhitespace
        )
        if let attributed = try? AttributedString(markdown: content, options: options) {
            return String(attributed.characters)
        }
        return content
    }

    func toDomain() -> OllamaMessage {
        OllamaMessage(
            id: id,
            content: content,
            role: role,
            images: imagesData.map { [$0] },
            createdAt: createdAt,
            model: model
        )
    }
}
